name: CI Build

on:
  workflow_dispatch:  # Manual trigger only
  pull_request:
    branches: [ master, main, develop ]  # Still auto-run on PRs

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          host: 'linux'
          target: 'desktop'
          cache: true
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            ninja-build
      
      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="${Qt6_DIR}" \
            -DCMAKE_WARN_DEPRECATED=OFF \
            -GNinja
      
      - name: Build EmberViewer
        run: |
          cd build
          ninja EmberViewer
      
      - name: Check EmberViewer binary
        run: |
          ls -lh build/EmberViewer/EmberViewer
          file build/EmberViewer/EmberViewer
          ldd build/EmberViewer/EmberViewer || true
      
      - name: Upload EmberViewer artifact
        uses: actions/upload-artifact@v4
        with:
          name: EmberViewer-linux-Release
          path: build/EmberViewer/EmberViewer
          retention-days: 7
      
      - name: Create/Update rolling pre-release
        if: github.ref == 'refs/heads/feature/ember-viewer' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-dev
          name: "Latest Development Build"
          prerelease: true
          draft: false
          files: build/EmberViewer/EmberViewer
          body: |
            ## 🚧 Development Build - Latest
            
            **Automatically built from:** `${{ github.ref_name }}`
            **Commit:** ${{ github.sha }}
            **Built:** ${{ github.event.head_commit.timestamp }}
            
            This is an **unstable development build**. Use at your own risk!
            
            ### Installation (Linux)
            ```bash
            chmod +x EmberViewer
            ./EmberViewer
            ```
            
            For stable releases, see: [Releases](https://github.com/${{ github.repository }}/releases)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  # Placeholder for future macOS builds
  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     # ... macOS specific steps
  
  # Placeholder for future Windows builds
  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     # ... Windows specific steps
