name: CI Build

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: /opt/qt
          key: ${{ runner.os }}-qt-5.15.2
      
      - name: Install Qt and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qtbase5-dev \
            qtbase5-dev-tools \
            qt5-qmake \
            cmake \
            build-essential \
            ninja-build
      
      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -GNinja
      
      - name: Build EmberViewer
        run: |
          cd build
          ninja EmberViewer
      
      - name: Check EmberViewer binary
        run: |
          ls -lh build/EmberViewer/EmberViewer
          file build/EmberViewer/EmberViewer
          ldd build/EmberViewer/EmberViewer || true
      
      - name: Upload EmberViewer artifact
        uses: actions/upload-artifact@v4
        with:
          name: EmberViewer-linux-Release
          path: build/EmberViewer/EmberViewer
          retention-days: 7
  
  # Placeholder for future macOS builds
  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     # ... macOS specific steps
  
  # Placeholder for future Windows builds
  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     # ... Windows specific steps
